name: decaarginine
channels:
- conda-forge
- omnia
dependencies:
- jupyter=1.0.0=py27_0
- matplotlib=2.0.2=np111py27_0
- mdtraj=1.7.2=np111py27_0
- pandas=0.20.2=np111py27_1
- numpy=1.11.3=py27_0
- python=2.7.13=0
- scipy=0.19.0=np111py27_0
- pdbfixer=1.4=py27_0
- statsmodels=0.8.0=py27_0
